### PR TITLE
Add PoshRSJob to Listing

### PR DESCRIPTION
**Pull request by proxb**

### CODE REVIEW

**Review by ClaudioESSilva — CHANGES_REQUESTED** [review]
Please remove the readme.md from the commit.
Otherwise, is perfect!

**Comment by ClaudioESSilva** [comment]
Thanks for sharing this @proxb !

**Comment by proxb** [comment]
Sure thing! I'll read up on how to do this or would it be fine to just remove my entry on the ReadMe so it is back to what it originally was?

**Comment by ClaudioESSilva** [comment]
Yes you can. Thanks.

**Pull request closed without merging**
