### PR TITLE
added rob's blog post on exporting permissions

### PR DESCRIPTION
**Pull request by ConstantineK**

### CODE REVIEW

**Comment by ClaudioESSilva** [comment]
Thanks for your contribution @ConstantineK .
Can you please add the twitter link for Rob's account?

With that is perfect.

**Comment by ConstantineK** [comment]
Oh right, great idea ;)

**Comment by ConstantineK** [comment]
Should be good to go.

**Review by ClaudioESSilva — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
